blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    about: Ask questions and have discussions with other users.
    url: https://github.com/Infiniticity/akinator.py/discussions